"""add_all_models

Revision ID: 972c4912b99a
Revises: 
Create Date: 2026-03-10 00:01:02.541975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '972c4912b99a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barrage',
    sa.Column('id_barrage', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=True),
    sa.Column('localisation_gps', sa.String(length=300), nullable=True),
    sa.Column('capacite_max_m3', sa.BigInteger(), nullable=True),
    sa.Column('seuil_reserve_m3', sa.BigInteger(), nullable=True),
    sa.Column('niveau_actuel_m3', sa.BigInteger(), nullable=True),
    sa.Column('derniere_maj', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_barrage')
    )
    op.create_index(op.f('ix_barrage_id_barrage'), 'barrage', ['id_barrage'], unique=False)
    op.create_table('cooperative',
    sa.Column('id_cooperative', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('superficie_ha', sa.DECIMAL(), nullable=True),
    sa.Column('types_cultures', sa.Text(), nullable=True),
    sa.Column('classe_priorite', sa.String(length=10), nullable=False),
    sa.Column('nom_contact', sa.String(length=200), nullable=True),
    sa.Column('email_contact', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id_cooperative')
    )
    op.create_index(op.f('ix_cooperative_id_cooperative'), 'cooperative', ['id_cooperative'], unique=False)
    op.create_table('utilisateur',
    sa.Column('id_utilisateur', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('mot_de_passe_hash', sa.String(length=300), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('derniere_connexion', sa.DateTime(), nullable=True),
    sa.Column('mfa_active', sa.Boolean(), nullable=False),
    sa.Column('sel_mfa', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_utilisateur')
    )
    op.create_index(op.f('ix_utilisateur_email'), 'utilisateur', ['email'], unique=True)
    op.create_index(op.f('ix_utilisateur_id_utilisateur'), 'utilisateur', ['id_utilisateur'], unique=False)
    op.create_table('capteur',
    sa.Column('id_capteur', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_barrage', sa.Integer(), nullable=True),
    sa.Column('type_capteur', sa.String(length=50), nullable=False),
    sa.Column('localisation', sa.String(length=300), nullable=True),
    sa.Column('unite_mesure', sa.String(length=50), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('derniere_calibration', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_barrage'], ['barrage.id_barrage'], ),
    sa.PrimaryKeyConstraint('id_capteur')
    )
    op.create_index(op.f('ix_capteur_id_capteur'), 'capteur', ['id_capteur'], unique=False)
    op.create_table('contrat',
    sa.Column('id_contrat', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cooperative', sa.Integer(), nullable=True),
    sa.Column('id_barrage', sa.Integer(), nullable=True),
    sa.Column('saison', sa.String(length=100), nullable=False),
    sa.Column('volume_contracte_m3', sa.BigInteger(), nullable=False),
    sa.Column('poids_priorite', sa.DECIMAL(), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_barrage'], ['barrage.id_barrage'], ),
    sa.ForeignKeyConstraint(['id_cooperative'], ['cooperative.id_cooperative'], ),
    sa.PrimaryKeyConstraint('id_contrat')
    )
    op.create_index(op.f('ix_contrat_id_contrat'), 'contrat', ['id_contrat'], unique=False)
    op.create_table('journal_audit',
    sa.Column('id_log', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_utilisateur', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entite_concernee', sa.String(length=200), nullable=True),
    sa.Column('id_entite', sa.Integer(), nullable=True),
    sa.Column('donnees_avant_json', sa.JSON(), nullable=True),
    sa.Column('donnees_apres_json', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('adresse_ip', sa.String(length=100), nullable=True),
    sa.Column('id_session', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateur.id_utilisateur'], ),
    sa.PrimaryKeyConstraint('id_log')
    )
    op.create_index(op.f('ix_journal_audit_id_log'), 'journal_audit', ['id_log'], unique=False)
    op.create_table('ordre_liberation',
    sa.Column('id_ordre', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_demandeur', sa.Integer(), nullable=True),
    sa.Column('id_approbateur', sa.Integer(), nullable=True),
    sa.Column('id_cooperative', sa.Integer(), nullable=True),
    sa.Column('volume_m3', sa.BigInteger(), nullable=False),
    sa.Column('timestamp_demande', sa.DateTime(), nullable=False),
    sa.Column('timestamp_decision', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('notes_approbation', sa.Text(), nullable=True),
    sa.Column('raison_blocage', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_approbateur'], ['utilisateur.id_utilisateur'], ),
    sa.ForeignKeyConstraint(['id_cooperative'], ['cooperative.id_cooperative'], ),
    sa.ForeignKeyConstraint(['id_demandeur'], ['utilisateur.id_utilisateur'], ),
    sa.PrimaryKeyConstraint('id_ordre')
    )
    op.create_index(op.f('ix_ordre_liberation_id_ordre'), 'ordre_liberation', ['id_ordre'], unique=False)
    op.create_table('resultat_prevision',
    sa.Column('id_prevision', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_barrage', sa.Integer(), nullable=True),
    sa.Column('date_generation', sa.DateTime(), nullable=False),
    sa.Column('version_modele', sa.String(length=100), nullable=True),
    sa.Column('niveaux_predits_json', sa.JSON(), nullable=True),
    sa.Column('intervalles_confiance_json', sa.JSON(), nullable=True),
    sa.Column('score_precision', sa.DECIMAL(), nullable=True),
    sa.Column('horizon_jours', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_barrage'], ['barrage.id_barrage'], ),
    sa.PrimaryKeyConstraint('id_prevision')
    )
    op.create_index(op.f('ix_resultat_prevision_id_prevision'), 'resultat_prevision', ['id_prevision'], unique=False)
    op.create_table('lecture_capteur',
    sa.Column('id_lecture', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_capteur', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('valeur', sa.DECIMAL(), nullable=False),
    sa.Column('indicateur_qualite', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_capteur'], ['capteur.id_capteur'], ),
    sa.PrimaryKeyConstraint('id_lecture')
    )
    op.create_index(op.f('ix_lecture_capteur_id_lecture'), 'lecture_capteur', ['id_lecture'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lecture_capteur_id_lecture'), table_name='lecture_capteur')
    op.drop_table('lecture_capteur')
    op.drop_index(op.f('ix_resultat_prevision_id_prevision'), table_name='resultat_prevision')
    op.drop_table('resultat_prevision')
    op.drop_index(op.f('ix_ordre_liberation_id_ordre'), table_name='ordre_liberation')
    op.drop_table('ordre_liberation')
    op.drop_index(op.f('ix_journal_audit_id_log'), table_name='journal_audit')
    op.drop_table('journal_audit')
    op.drop_index(op.f('ix_contrat_id_contrat'), table_name='contrat')
    op.drop_table('contrat')
    op.drop_index(op.f('ix_capteur_id_capteur'), table_name='capteur')
    op.drop_table('capteur')
    op.drop_index(op.f('ix_utilisateur_id_utilisateur'), table_name='utilisateur')
    op.drop_index(op.f('ix_utilisateur_email'), table_name='utilisateur')
    op.drop_table('utilisateur')
    op.drop_index(op.f('ix_cooperative_id_cooperative'), table_name='cooperative')
    op.drop_table('cooperative')
    op.drop_index(op.f('ix_barrage_id_barrage'), table_name='barrage')
    op.drop_table('barrage')
    # ### end Alembic commands ###
