"""refine_types_to_match_er_diagram

Revision ID: e41a5e35523b
Revises: 972c4912b99a
Create Date: 2026-03-12 00:41:40.850453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e41a5e35523b'
down_revision: Union[str, None] = '972c4912b99a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barrage', sa.Column('safety_reserve_pct', sa.Float(), nullable=False))
    op.add_column('barrage', sa.Column('current_level_pct', sa.Float(), nullable=False))
    op.add_column('barrage', sa.Column('safety_lock_active', sa.Boolean(), nullable=True))
    op.add_column('barrage', sa.Column('current_zone', sa.String(length=50), nullable=True))
    op.add_column('capteur', sa.Column('name', sa.String(length=100), nullable=True))
    op.alter_column('capteur', 'id_capteur',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('contrat', sa.Column('effective_allocation_m3', sa.Float(), nullable=True))
    op.add_column('contrat', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('journal_audit', sa.Column('user_name', sa.String(length=200), nullable=True))
    op.add_column('journal_audit', sa.Column('user_role', sa.String(length=50), nullable=True))
    op.add_column('journal_audit', sa.Column('extra_notes', sa.Text(), nullable=True))
    op.alter_column('journal_audit', 'id_log',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('lecture_capteur', 'id_lecture',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('ordre_liberation', sa.Column('dam_id', sa.Integer(), nullable=True))
    op.add_column('ordre_liberation', sa.Column('is_override', sa.String(length=5), nullable=True))
    op.add_column('ordre_liberation', sa.Column('override_justification', sa.Text(), nullable=True))
    op.add_column('ordre_liberation', sa.Column('override_mfa_verified', sa.String(length=5), nullable=True))
    op.add_column('ordre_liberation', sa.Column('ai_recommendation', sa.Text(), nullable=True))
    op.add_column('ordre_liberation', sa.Column('scheduled_release_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'ordre_liberation', 'barrage', ['dam_id'], ['id_barrage'])
    op.add_column('resultat_prevision', sa.Column('forecast_data', sa.JSON(), nullable=True))
    op.add_column('resultat_prevision', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resultat_prevision', 'notes')
    op.drop_column('resultat_prevision', 'forecast_data')
    op.drop_constraint(None, 'ordre_liberation', type_='foreignkey')
    op.drop_column('ordre_liberation', 'scheduled_release_at')
    op.drop_column('ordre_liberation', 'ai_recommendation')
    op.drop_column('ordre_liberation', 'override_mfa_verified')
    op.drop_column('ordre_liberation', 'override_justification')
    op.drop_column('ordre_liberation', 'is_override')
    op.drop_column('ordre_liberation', 'dam_id')
    op.alter_column('lecture_capteur', 'id_lecture',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('journal_audit', 'id_log',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('journal_audit', 'extra_notes')
    op.drop_column('journal_audit', 'user_role')
    op.drop_column('journal_audit', 'user_name')
    op.drop_column('contrat', 'notes')
    op.drop_column('contrat', 'effective_allocation_m3')
    op.alter_column('capteur', 'id_capteur',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('capteur', 'name')
    op.drop_column('barrage', 'current_zone')
    op.drop_column('barrage', 'safety_lock_active')
    op.drop_column('barrage', 'current_level_pct')
    op.drop_column('barrage', 'safety_reserve_pct')
    # ### end Alembic commands ###
