"""
Core Security Module.
Handles Password Hashing, JWT encoding/decoding, and MFA generation/verification.
"""

import uuid
from datetime import datetime, timedelta
from typing import Any, Dict, Optional, Tuple

import pyotp
import bcrypt
from jose import JWTError, jwt

from app.config import settings

# ── Password Hashing ────────────────────────────────────────────────


def verify_password(plain_password: str, hashed_password: str) -> bool:
    """Verify a plain password against its hash."""
    return bcrypt.checkpw(plain_password.encode('utf-8'), hashed_password.encode('utf-8'))


def get_password_hash(password: str) -> str:
    """Generate bcrypt hash for a password."""
    # salt is automatically generated by bcrypt
    return bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')


# ── JWT Token Management ────────────────────────────────────────────
def create_access_token(
    subject: str | int, role: str, expires_delta: Optional[timedelta] = None
) -> Tuple[str, str, datetime]:
    """
    Generate a new JWT Access Token.
    Returns: (token_string, jti_id, expires_at_datetime)
    """
    if expires_delta:
        expire = datetime.utcnow() + expires_delta
    else:
        expire = datetime.utcnow() + timedelta(minutes=settings.ACCESS_TOKEN_EXPIRE_MINUTES)
    
    jti = str(uuid.uuid4())
    to_encode = {
        "sub": str(subject),
        "role": role,
        "type": "access",
        "jti": jti,
        "exp": expire,
    }
    encoded_jwt = jwt.encode(to_encode, settings.SECRET_KEY, algorithm=settings.ALGORITHM)
    return encoded_jwt, jti, expire


def create_refresh_token(
    subject: str | int, expires_delta: Optional[timedelta] = None
) -> Tuple[str, str, datetime]:
    """
    Generate a new JWT Refresh Token.
    Returns: (token_string, jti_id, expires_at_datetime)
    """
    if expires_delta:
        expire = datetime.utcnow() + expires_delta
    else:
        expire = datetime.utcnow() + timedelta(days=settings.REFRESH_TOKEN_EXPIRE_DAYS)
        
    jti = str(uuid.uuid4())
    to_encode = {
        "sub": str(subject),
        "type": "refresh",
        "jti": jti,
        "exp": expire,
    }
    encoded_jwt = jwt.encode(to_encode, settings.SECRET_KEY, algorithm=settings.ALGORITHM)
    return encoded_jwt, jti, expire


def create_mfa_token(
    subject: str | int, expires_delta: Optional[timedelta] = None
) -> Tuple[str, str, datetime]:
    """
    Generate a short-lived token to prove MFA was recently verified.
    Returns: (token_string, jti_id, expires_at_datetime)
    """
    # E.g., a 10-minute token to allow override actions
    expire = datetime.utcnow() + (expires_delta or timedelta(minutes=10))
    jti = str(uuid.uuid4())
    to_encode = {
        "sub": str(subject),
        "type": "mfa_verified",
        "jti": jti,
        "exp": expire,
    }
    encoded_jwt = jwt.encode(to_encode, settings.SECRET_KEY, algorithm=settings.ALGORITHM)
    return encoded_jwt, jti, expire


def decode_token(token: str) -> Optional[Dict[str, Any]]:
    """Decode and verify a JWT token. Returns None if invalid/expired."""
    try:
        payload = jwt.decode(token, settings.SECRET_KEY, algorithms=[settings.ALGORITHM])
        return payload
    except JWTError:
        return None


# ── MFA (TOTP) Management ───────────────────────────────────────────
def generate_mfa_secret() -> str:
    """Generate a random base32 encoded MFA secret."""
    return pyotp.random_base32()


def get_mfa_provisioning_uri(secret: str, email: str) -> str:
    """Generate a provisioning URI for Google Authenticator/Authy."""
    return pyotp.totp.TOTP(secret).provisioning_uri(
        name=email, issuer_name=settings.MFA_ISSUER
    )


def verify_mfa_code(secret: str, code: str) -> bool:
    """Verify a 6-digit TOTP code against a secret."""
    totp = pyotp.TOTP(secret)
    return totp.verify(code)
